version: '2'
services:
  gitlab:
    network_mode: bridge
    image: gitlab/gitlab-ce:latest
    hostname: 'gitlab.local'
    restart: always
    environment:
     GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.99.10'
    volumes:
      - 'config:/etc/gitlab'
      - 'logs:/var/log/gitlab'
      - 'data:/var/opt/gitlab'
    ports:
      - '7080:80'
      - '7443:443'
      - '7022:22'
    environment:
      - VIRTUAL_HOST=gitlab.local
volumes:
  config: {}
  logs: {}
  data: {}

